### ISSUE TITLE
String Check on line 40 always erroring

### ISSUE THREAD

**Issue by mfishes** [aviolaris/instaunfollowers#1]
Hi! This is an extremely handy little app, but was running into the 'html_source must be a string' error a lot, and it's because html_source isn't a string. I fixed it by _setting_ it to a string in the regex call (see below), but you may have a different issue you're solving for.
`return re.findall(links_usernames_regexp, str(html_source))`

**Comment by aviolaris** [comment]
Thank you for bringing this issue to my attention. I appreciate your feedback and your efforts in finding a solution.

The code you suggested as a fix is actually the original code from the initial commit. As you have correctly guessed, I made some modifications to it in order to enable unit testing. Unfortunately, I forgot to decode the bytes objects which resulted in the error you encountered.

I have addressed the issue in the new release, so please let me know if you encounter any further issues.
